parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     3306
    database_name:     root
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       
    mailer_password:   

    locale:            ru
    secret:            security

    debug_toolbar:          true
    debug_redirects:        false
    use_assetic_controller: true