sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_admin:
    title:      "Symfony-Base"
    options:
        pager_links: 10
        title_mode: 'single_text'
    templates:
        layout: ApplicationSonataAdminBundle::standard_layout_override.html.twig
        select: ApplicationSonataAdminBundle:CRUD:list__select_override.html.twig
        user_block: ApplicationSonataAdminBundle:block:user_block.html.twig